name: Patient-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "REACT_APP_SERVER_URL=https://ftmwsamij8.execute-api.us-east-1.amazonaws.com/SNS/SNS_SQS_API" >> .env
          echo "REACT_APP_GOOGLE_CLIENT_ID=800791470976-1f80oefd548j7sjur57aik26crj4vpuc.apps.googleusercontent.com" >> .env

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
