name: Patient-frontend
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "REACT_APP_SERVER_URL=https://ftmwsamij8.execute-api.us-east-1.amazonaws.com/SNS/SNS_SQS_API" >> .env
          echo "REACT_APP_GOOGLE_CLIENT_ID=800791470976-1f80oefd548j7sjur57aik26crj4vpuc.apps.googleusercontent.com" >> .env
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t prasannakumar012/patient-frontend .
      - name: Push image to Docker Hub
        run: docker push prasannakumar012/patient-frontend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull prasannakumar012/patient-frontend:latest
      - name: Delete old container
        run: docker rm -f patient-frontend-container || true
      - name: Run Docker container
        run: docker run -d -p 80:80 --name patient-frontend-container prasannakumar012/patient-frontend






